export const mockProducts = [
  {
    id: "1",
    name: "Red Roses Premium",
    category: "Roses",
    color: "Red",
    variety: "Red Pearl",
    stem_length: "60cm",
    packaging_type: "Box of 50",
    description: "Premium red roses, 60cm stems, fresh from plantation",
    price_per_unit: 0.85,
    price_per_box: 45,
    stock_quantity: 500,
    min_order_quantity: 50,
    next_delivery_date: "2025-01-10",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Pink Roses Deluxe",
    category: "Roses",
    color: "Pink",
    variety: "Pink Lady",
    stem_length: "60cm",
    packaging_type: "Box of 50",
    description: "Soft pink roses, 60cm stems, perfect for arrangements",
    price_per_unit: 0.95,
    price_per_box: 50,
    stock_quantity: 300,
    min_order_quantity: 50,
    next_delivery_date: "2025-01-10",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "3",
    name: "White Roses Classic",
    category: "Roses",
    color: "White",
    variety: "Avalanche",
    stem_length: "70cm",
    packaging_type: "Box of 50",
    description: "Pure white roses, 70cm stems, premium quality",
    price_per_unit: 1.2,
    price_per_box: 60,
    stock_quantity: 250,
    min_order_quantity: 50,
    next_delivery_date: "2025-01-10",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Yellow Chrysanthemums",
    category: "Chrysanthemums",
    color: "Yellow",
    variety: "Santini",
    stem_length: "50cm",
    packaging_type: "Box of 100",
    description: "Bright yellow chrysanthemums, 50cm stems",
    price_per_unit: 0.45,
    price_per_box: 30,
    stock_quantity: 600,
    min_order_quantity: 100,
    next_delivery_date: "2025-01-08",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "5",
    name: "White Chrysanthemums",
    category: "Chrysanthemums",
    color: "White",
    variety: "Daisy",
    stem_length: "50cm",
    packaging_type: "Box of 100",
    description: "Pure white chrysanthemums, fresh and vibrant",
    price_per_unit: 0.4,
    price_per_box: 25,
    stock_quantity: 800,
    min_order_quantity: 100,
    next_delivery_date: "2025-01-08",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Red Carnations",
    category: "Carnations",
    color: "Red",
    variety: "Premium",
    stem_length: "60cm",
    packaging_type: "Box of 100",
    description: "Deep red carnations, 60cm stems, long lasting",
    price_per_unit: 0.3,
    price_per_box: 20,
    stock_quantity: 1000,
    min_order_quantity: 100,
    next_delivery_date: "2025-01-09",
    plantation_country: "China",
    created_at: "2024-12-01T00:00:00Z",
  },
]

export const mockUsers = [
  {
    id: "user-1",
    email: "customer@example.com",
    company_name: "Flower Shop Almaty",
    contact_person: "Anna Petrova",
    phone: "+7 777 123 4567",
    role: "customer",
    created_at: "2024-11-15T00:00:00Z",
  },
  {
    id: "user-2",
    email: "shop@example.com",
    company_name: "Bouquet Master",
    contact_person: "Ivan Ivanov",
    phone: "+7 777 234 5678",
    role: "customer",
    created_at: "2024-11-20T00:00:00Z",
  },
]

export const mockEmployees = [
  {
    id: "emp-1",
    email: "employee@greenflowers.kz",
    role: "employee",
    created_at: "2024-10-01T00:00:00Z",
  },
  {
    id: "admin-1",
    email: "admin@greenflowers.kz",
    role: "admin",
    created_at: "2024-09-01T00:00:00Z",
  },
]

export const mockOrders = [
  {
    id: "order-001",
    user_id: "user-1",
    total_amount: 425,
    delivery_city: "Almaty",
    delivery_address: "123 Main St",
    delivery_date: "2025-01-15",
    payment_method: "kaspi_qr",
    notes: "",
    status: "pending",
    created_at: "2024-12-28T00:00:00Z",
    order_items: [
      { id: "item-1", product_id: "1", quantity: 100, unit_price: 0.85, products: { name: "Red Roses Premium" } },
      { id: "item-2", product_id: "4", quantity: 500, unit_price: 0.45, products: { name: "Yellow Chrysanthemums" } },
    ],
  },
  {
    id: "order-002",
    user_id: "user-2",
    total_amount: 240,
    delivery_city: "Astana",
    delivery_address: "456 Oak Ave",
    delivery_date: "2025-01-12",
    payment_method: "kaspi_manual",
    notes: "Please call before delivery",
    status: "confirmed",
    created_at: "2024-12-27T00:00:00Z",
    order_items: [
      { id: "item-3", product_id: "2", quantity: 200, unit_price: 0.95, products: { name: "Pink Roses Deluxe" } },
      { id: "item-4", product_id: "6", quantity: 100, unit_price: 0.3, products: { name: "Red Carnations" } },
    ],
  },
  {
    id: "order-003",
    user_id: "user-1",
    total_amount: 180,
    delivery_city: "Almaty",
    delivery_address: "123 Main St",
    delivery_date: "2025-01-10",
    payment_method: "cash_on_delivery",
    notes: "",
    status: "delivered",
    created_at: "2024-12-20T00:00:00Z",
    order_items: [
      { id: "item-5", product_id: "3", quantity: 150, unit_price: 1.2, products: { name: "White Roses Classic" } },
    ],
  },
]

export const mockPreorders = [
  {
    id: "preorder-001",
    user_id: "user-1",
    product_id: "1",
    quantity: 500,
    desired_delivery_date: "2025-02-14",
    order_type: "holiday_preorder",
    holiday_type: "valentines_day",
    status: "pending",
    created_at: "2024-12-25T00:00:00Z",
    products: { name: "Red Roses Premium" },
  },
  {
    id: "preorder-002",
    user_id: "user-2",
    product_id: "2",
    quantity: 200,
    desired_delivery_date: "2025-03-08",
    order_type: "holiday_preorder",
    holiday_type: "women_day",
    status: "confirmed",
    created_at: "2024-12-26T00:00:00Z",
    products: { name: "Pink Roses Deluxe" },
  },
]

export const mockDeliveryZones = [
  { id: "zone-1", city_name: "Almaty", delivery_fee: 0, delivery_days: 1, is_active: true },
  { id: "zone-2", city_name: "Astana", delivery_fee: 15, delivery_days: 2, is_active: true },
  { id: "zone-3", city_name: "Shymkent", delivery_fee: 20, delivery_days: 2, is_active: true },
  { id: "zone-4", city_name: "Karaganda", delivery_fee: 18, delivery_days: 2, is_active: true },
  { id: "zone-5", city_name: "Aktobe", delivery_fee: 25, delivery_days: 3, is_active: true },
]

export const mockDeliverySchedules = [
  {
    id: "sched-1",
    shipment_date: "2025-01-05",
    expected_arrival_date: "2025-01-08",
    quantity_available: 5000,
    status: "shipped",
  },
  {
    id: "sched-2",
    shipment_date: "2025-01-10",
    expected_arrival_date: "2025-01-13",
    quantity_available: 8000,
    status: "planned",
  },
  {
    id: "sched-3",
    shipment_date: "2025-01-15",
    expected_arrival_date: "2025-01-18",
    quantity_available: 6000,
    status: "planned",
  },
]

export const mockCartItems: any[] = []
