export interface Product {
  id: number
  name: string
  nameRu?: string
  nameKk?: string
  category: string
  description: string
  descriptionRu?: string
  descriptionKk?: string
  color: string
  variety: string
  stemLength: string
  packaging: string
  minOrder: number
  pricePerUnit: number
  pricePerBox: number
  season: string
  imageUrl: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Red Roses Premium",
    nameRu: "Розы красные Premium",
    nameKk: "Қызыл раушандар Premium",
    category: "roses",
    description:
      "Premium red roses from Kunming, 60cm stems, fresh from plantation. Perfect for bouquets and arrangements.",
    descriptionRu:
      "Премиальные красные розы из Куньмина, стебель 60см, свежие с плантации. Идеальны для букетов и композиций.",
    descriptionKk:
      "Куньминнен премиум қызыл раушандар, сабағы 60см, плантациядан таза. Букеттер мен композициялар үшін тамаша.",
    color: "red",
    variety: "Red Pearl",
    stemLength: "60cm",
    packaging: "25 stems/box",
    minOrder: 2,
    pricePerUnit: 850,
    pricePerBox: 21250,
    season: "yearRound",
    imageUrl: "/premium-red-roses-bouquet.jpg",
  },
  {
    id: 2,
    name: "Pink Roses Deluxe",
    nameRu: "Розы розовые Deluxe",
    nameKk: "Қызғылт раушандар Deluxe",
    category: "roses",
    description: "Soft pink roses, 60cm stems, perfect for romantic arrangements and weddings.",
    descriptionRu: "Нежно-розовые розы, стебель 60см, идеальны для романтических композиций и свадеб.",
    descriptionKk: "Нәзік қызғылт раушандар, сабағы 60см, романтикалық композициялар мен тойлар үшін тамаша.",
    color: "pink",
    variety: "Pink Lady",
    stemLength: "60cm",
    packaging: "25 stems/box",
    minOrder: 2,
    pricePerUnit: 950,
    pricePerBox: 23750,
    season: "yearRound",
    imageUrl: "/pink-roses-deluxe-wedding.jpg",
  },
  {
    id: 3,
    name: "White Roses Avalanche",
    nameRu: "Розы белые Avalanche",
    nameKk: "Ақ раушандар Avalanche",
    category: "roses",
    description: "Pure white Avalanche roses, 70cm stems, premium quality for weddings and special events.",
    descriptionRu: "Чисто-белые розы Avalanche, стебель 70см, премиум качество для свадеб и особых мероприятий.",
    descriptionKk: "Таза ақ Avalanche раушандары, сабағы 70см, тойлар мен ерекше іс-шаралар үшін премиум сапа.",
    color: "white",
    variety: "Avalanche",
    stemLength: "70cm",
    packaging: "25 stems/box",
    minOrder: 2,
    pricePerUnit: 1200,
    pricePerBox: 30000,
    season: "yearRound",
    imageUrl: "/white-avalanche-roses-wedding.jpg",
  },
  {
    id: 4,
    name: "Yellow Chrysanthemums Santini",
    nameRu: "Хризантемы жёлтые Santini",
    nameKk: "Сары хризантемалар Santini",
    category: "chrysanthemums",
    description: "Bright yellow Santini chrysanthemums, 50cm stems. Long-lasting, perfect for arrangements.",
    descriptionRu: "Ярко-жёлтые хризантемы Santini, стебель 50см. Долго стоят, идеальны для композиций.",
    descriptionKk: "Жарқын сары Santini хризантемалары, сабағы 50см. Ұзақ тұрады, композициялар үшін тамаша.",
    color: "yellow",
    variety: "Santini",
    stemLength: "50cm",
    packaging: "50 stems/box",
    minOrder: 1,
    pricePerUnit: 450,
    pricePerBox: 22500,
    season: "yearRound",
    imageUrl: "/yellow-santini-chrysanthemums.jpg",
  },
  {
    id: 5,
    name: "White Chrysanthemums Spray",
    nameRu: "Хризантемы белые кустовые",
    nameKk: "Ақ бұталы хризантемалар",
    category: "chrysanthemums",
    description: "Pure white spray chrysanthemums, fresh and vibrant. Great for funeral arrangements and bouquets.",
    descriptionRu:
      "Чисто-белые кустовые хризантемы, свежие и яркие. Отлично подходят для траурных композиций и букетов.",
    descriptionKk: "Таза ақ бұталы хризантемалар, таза және жарқын. Қайғылы композициялар мен букеттер үшін тамаша.",
    color: "white",
    variety: "Spray",
    stemLength: "50cm",
    packaging: "50 stems/box",
    minOrder: 1,
    pricePerUnit: 400,
    pricePerBox: 20000,
    season: "yearRound",
    imageUrl: "/white-spray-chrysanthemums.jpg",
  },
  {
    id: 6,
    name: "Red Carnations Premium",
    nameRu: "Гвоздики красные Premium",
    nameKk: "Қызыл қалампырлар Premium",
    category: "carnations",
    description: "Deep red carnations, 60cm stems, long lasting. Perfect for mixed bouquets and arrangements.",
    descriptionRu:
      "Насыщенные красные гвоздики, стебель 60см, долго стоят. Идеальны для смешанных букетов и композиций.",
    descriptionKk: "Қою қызыл қалампырлар, сабағы 60см, ұзақ тұрады. Аралас букеттер мен композициялар үшін тамаша.",
    color: "red",
    variety: "Premium",
    stemLength: "60cm",
    packaging: "50 stems/box",
    minOrder: 1,
    pricePerUnit: 300,
    pricePerBox: 15000,
    season: "yearRound",
    imageUrl: "/red-carnations-premium.jpg",
  },
  {
    id: 7,
    name: "Pink Carnations Standard",
    nameRu: "Гвоздики розовые Standard",
    nameKk: "Қызғылт қалампырлар Standard",
    category: "carnations",
    description: "Light pink carnations, perfect for bouquets and everyday arrangements.",
    descriptionRu: "Светло-розовые гвоздики, идеальны для букетов и повседневных композиций.",
    descriptionKk: "Ашық қызғылт қалампырлар, букеттер мен күнделікті композициялар үшін тамаша.",
    color: "pink",
    variety: "Standard",
    stemLength: "60cm",
    packaging: "50 stems/box",
    minOrder: 1,
    pricePerUnit: 280,
    pricePerBox: 14000,
    season: "yearRound",
    imageUrl: "/pink-carnations.jpg",
  },
  {
    id: 8,
    name: "Gypsophila Million Star",
    nameRu: "Гипсофила Million Star",
    nameKk: "Гипсофила Million Star",
    category: "gypsophila",
    description: "Delicate white gypsophila, perfect filler flower for any arrangement. Creates airy, romantic look.",
    descriptionRu:
      "Нежная белая гипсофила, идеальный наполнитель для любой композиции. Создаёт воздушный, романтичный образ.",
    descriptionKk:
      "Нәзік ақ гипсофила, кез келген композиция үшін тамаша толтырғыш. Ауалы, романтикалық көрініс жасайды.",
    color: "white",
    variety: "Million Star",
    stemLength: "60cm",
    packaging: "25 bunches/box",
    minOrder: 1,
    pricePerUnit: 600,
    pricePerBox: 15000,
    season: "yearRound",
    imageUrl: "/gypsophila-baby-breath-white.jpg",
  },
  {
    id: 9,
    name: "Oriental Lilies Pink",
    nameRu: "Лилии восточные розовые",
    nameKk: "Шығыс лилиялары қызғылт",
    category: "lilies",
    description: "Fragrant pink oriental lilies, 80cm stems. Strong fragrance, large blooms.",
    descriptionRu: "Ароматные розовые восточные лилии, стебель 80см. Сильный аромат, крупные цветы.",
    descriptionKk: "Хош иісті қызғылт шығыс лилиялары, сабағы 80см. Күшті хош иіс, ірі гүлдер.",
    color: "pink",
    variety: "Sorbonne",
    stemLength: "80cm",
    packaging: "10 stems/box",
    minOrder: 2,
    pricePerUnit: 2500,
    pricePerBox: 25000,
    season: "yearRound",
    imageUrl: "/pink-oriental-lilies.jpg",
  },
  {
    id: 10,
    name: "White Lilies Casablanca",
    nameRu: "Лилии белые Casablanca",
    nameKk: "Ақ лилиялар Casablanca",
    category: "lilies",
    description: "Pure white Casablanca lilies, most prestigious variety. Ideal for weddings and luxury events.",
    descriptionRu:
      "Чисто-белые лилии Casablanca, самый престижный сорт. Идеальны для свадеб и премиальных мероприятий.",
    descriptionKk: "Таза ақ Casablanca лилиялары, ең беделді сорт. Тойлар мен премиум іс-шаралар үшін тамаша.",
    color: "white",
    variety: "Casablanca",
    stemLength: "80cm",
    packaging: "10 stems/box",
    minOrder: 2,
    pricePerUnit: 3000,
    pricePerBox: 30000,
    season: "yearRound",
    imageUrl: "/white-casablanca-lilies.jpg",
  },
  {
    id: 11,
    name: "Gerberas Mix Bright",
    nameRu: "Герберы микс яркие",
    nameKk: "Гербералар микс жарқын",
    category: "gerberas",
    description: "Vibrant mixed gerberas in bright colors. Perfect for cheerful arrangements and gifts.",
    descriptionRu: "Яркие герберы микс в ярких цветах. Идеальны для весёлых композиций и подарков.",
    descriptionKk: "Жарқын түстердегі жарқын микс гербералар. Көңілді композициялар мен сыйлықтар үшін тамаша.",
    color: "multi",
    variety: "Mix Standard",
    stemLength: "50cm",
    packaging: "50 stems/box",
    minOrder: 1,
    pricePerUnit: 550,
    pricePerBox: 27500,
    season: "yearRound",
    imageUrl: "/colorful-gerbera-daisies-mix.jpg",
  },
  {
    id: 12,
    name: "Tulips Spring Collection",
    nameRu: "Тюльпаны весенняя коллекция",
    nameKk: "Қызғалдақтар көктемгі коллекция",
    category: "seasonal",
    description: "Spring tulips in assorted colors. Available February-April. Pre-order recommended.",
    descriptionRu: "Весенние тюльпаны в ассортименте. Доступны февраль-апрель. Рекомендуем предзаказ.",
    descriptionKk:
      "Көктемгі қызғалдақтар әр түрлі түстерде. Ақпан-сәуір аралығында қолжетімді. Алдын ала тапсырыс ұсынамыз.",
    color: "multi",
    variety: "Spring Mix",
    stemLength: "45cm",
    packaging: "50 stems/box",
    minOrder: 2,
    pricePerUnit: 700,
    pricePerBox: 35000,
    season: "spring",
    imageUrl: "/colorful-spring-tulips.jpg",
  },
  {
    id: 13,
    name: "Valentine's Red Mix",
    nameRu: "Валентинов микс красный",
    nameKk: "Валентин күні қызыл микс",
    category: "holiday",
    description: "Special Valentine's collection: red roses, red carnations, and gypsophila. Perfect romantic gift.",
    descriptionRu:
      "Специальная коллекция ко Дню Валентина: красные розы, красные гвоздики и гипсофила. Идеальный романтический подарок.",
    descriptionKk:
      "Валентин күніне арналған арнайы коллекция: қызыл раушандар, қызыл қалампырлар және гипсофила. Тамаша романтикалық сыйлық.",
    color: "red",
    variety: "Valentine Special",
    stemLength: "60cm",
    packaging: "Mixed box",
    minOrder: 1,
    pricePerUnit: 1800,
    pricePerBox: 90000,
    season: "winter",
    imageUrl: "/valentine-red-roses-romantic.jpg",
  },
  {
    id: 14,
    name: "8 March Women's Day Mix",
    nameRu: "8 Марта микс",
    nameKk: "8 Наурыз микс",
    category: "holiday",
    description: "Special Women's Day collection with tulips, roses, and mimosa. Pre-order for March delivery.",
    descriptionRu: "Специальная коллекция к 8 Марта: тюльпаны, розы и мимоза. Предзаказ на мартовскую поставку.",
    descriptionKk:
      "8 Наурызға арналған арнайы коллекция: қызғалдақтар, раушандар және мимоза. Наурыз жеткізуіне алдын ала тапсырыс.",
    color: "multi",
    variety: "March 8 Special",
    stemLength: "50cm",
    packaging: "Mixed box",
    minOrder: 1,
    pricePerUnit: 1500,
    pricePerBox: 75000,
    season: "spring",
    imageUrl: "/womens-day-flowers-tulips-mimosa.jpg",
  },
  {
    id: 15,
    name: "Purple Roses Ecuador",
    nameRu: "Розы фиолетовые Ecuador",
    nameKk: "Күлгін раушандар Ecuador",
    category: "roses",
    description: "Unique purple roses, rare variety from premium Ecuador plantations via China.",
    descriptionRu: "Уникальные фиолетовые розы, редкий сорт с премиальных плантаций Эквадора через Китай.",
    descriptionKk: "Бірегей күлгін раушандар, Қытай арқылы премиум Эквадор плантацияларынан сирек сорт.",
    color: "purple",
    variety: "Purple Haze",
    stemLength: "70cm",
    packaging: "25 stems/box",
    minOrder: 2,
    pricePerUnit: 1500,
    pricePerBox: 37500,
    season: "yearRound",
    imageUrl: "/purple-roses-ecuador-premium.jpg",
  },
]
